### ISSUE TITLE
WSOD when trying to activate

### ISSUE THREAD

**Issue by pjbarry21** [buddypress/bp-attachments#24] opened 2016-05-23 04:39 UTC
Installed on WP 4.5.2, BP 2.5.2, and Boss theme. Any thoughts on what might be the cause or a potential fix? Sorry, no idea where to start looking. Once I deleted the plugin directory for it the site came back up.

**Comment by imath** [comment] 2016-05-23 07:39
What about the error log. If you have a white screen of death, it's probably a fatal error. It could be the duplicate use of a function name for instance.

I've just rechecked with a fresh WordPress install, i don't manage to reproduce. Have you tried to deactivate the Boss theme ?

**Comment by pjbarry21** [comment] 2016-05-24 12:17
Thanks for the suggestion -- still finding my way around in WP (spent the last 5+ years in Drupal).

Here's what I get in the error log once I click activate and get the WSOD (and I got this using another theme, too):

`[Tue May 24 11:50:45.579305 2016] [:error] [pid 17254] [client 68.226.109.173:12245] PHP Warning:  require(/nas/content/live/healthdoers/wp-content/plugins/bp-attachments/bp-attachments/bp-attachments-loader.php): failed to open stream: No such file or directory in /nas/content/live/healthdoers/wp-content/plugins/bp-attachments/loader.php on line 189, referer: http://open.healthdoers.org/wp-admin/plugins.php
[Tue May 24 11:50:45.579427 2016] [:error] [pid 17254] [client 68.226.109.173:12245] PHP Fatal error:  require(): Failed opening required '/nas/content/live/healthdoers/wp-content/plugins/bp-attachments/bp-attachments/bp-attachments-loader.php' (include_path='.:/usr/share/php:/usr/share/pear') in /nas/content/live/healthdoers/wp-content/plugins/bp-attachments/loader.php on line 189, referer: http://open.healthdoers.org/wp-admin/plugins.php
[Tue May 24 11:50:50.060076 2016] [:error] [pid 17256] [client 68.226.109.173:12250] PHP Warning:  require(/nas/content/live/healthdoers/wp-content/plugins/bp-attachments/bp-attachments/bp-attachments-loader.php): failed to open stream: No such file or directory in /nas/content/live/healthdoers/wp-content/plugins/bp-attachments/loader.php on line 189, referer: http://open.healthdoers.org/wp-admin/plugins.php
[Tue May 24 11:50:50.060191 2016] [:error] [pid 17256] [client 68.226.109.173:12250] PHP Fatal error:  require(): Failed opening required '/nas/content/live/healthdoers/wp-content/plugins/bp-attachments/bp-attachments/bp-attachments-loader.php' (include_path='.:/usr/share/php:/usr/share/pear') in /nas/content/live/healthdoers/wp-content/plugins/bp-attachments/loader.php on line 189, referer: http://open.healthdoers.org/wp-admin/plugins.php
[Tue May 24 11:50:52.798158 2016] [:error] [pid 17255] [client 68.226.109.173:12256] PHP Warning:  require(/nas/content/live/healthdoers/wp-content/plugins/bp-attachments/bp-attachments/bp-attachments-loader.php): failed to open stream: No such file or directory in /nas/content/live/healthdoers/wp-content/plugins/bp-attachments/loader.php on line 189, referer: http://open.healthdoers.org/wp-admin/plugins.php
[Tue May 24 11:50:52.798263 2016] [:error] [pid 17255] [client 68.226.109.173:12256] PHP Fatal error:  require(): Failed opening required '/nas/content/live/healthdoers/wp-content/plugins/bp-attachments/bp-attachments/bp-attachments-loader.php' (include_path='.:/usr/share/php:/usr/share/pear') in /nas/content/live/healthdoers/wp-content/plugins/bp-attachments/loader.php on line 189, referer: http://open.healthdoers.org/wp-admin/plugins.php`

I've confirmed that bp-attachments-loader.php is in the main bp-attachments directory. Should it be elsewhere?

Thanks!
Pam

**Comment by dcavins** [comment] 2016-05-24 13:26
If you can confirm the file exists, the next step is to check the permissions on the file. Which user owns it, and can other users (like php) read it?

**Comment by pjbarry21** [comment] 2016-05-24 13:50
I purged the cache and "reset all permissions" in the wp-engine dashboard (and saw the permissions change using my ftp client) and no change.

**Comment by r-a-y** [comment] 2016-05-24 16:32
Maybe start from scratch and delete your `bp-attachments` folder and reupload a fresh one.

If you are using the [ZIP file](https://github.com/buddypress/bp-attachments/archive/master.zip), make sure you do not omit any files or directories.

**Comment by pjbarry21** [comment] 2016-05-24 16:34
Thanks. I've tried that -- and redownloaded from the repository, too.

**Comment by imath** [comment] 2019-10-07 07:48
Hi, sorry I haven't updated this repository for a while, I'm going to close this issue because I will completely rewrite this plugin so that it enjoys latest WordPress and BuddyPress improvements.

**Closed by imath** 2019-10-07 07:48 UTC
